### ISSUE TITLE
raise StopIteration

### ISSUE THREAD

**Issue by fmorenovr** [CSAILVision/NetDissect-Lite#20]
I ran "python main.py" and I got:

labelprobe image index 63296, items per sec 99.2679, 126.2880

Traceback (most recent call last):
  File "/home/jenazads/github/NetDissect-Lite/loader/data_loader.py", line 518, in batches
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 18, in <module>
    tally_result = fo.tally(features[layer_id],thresholds,savepath="tally.csv")
  File "/home/jenazads/github/NetDissect-Lite/feature_operation.py", line 216, in tally
    FeatureOperator.tally_job((features, self.data, threshold, tally_labels, tally_units, tally_units_cat, tally_both, 0, self.data.size()))
  File "/home/jenazads/github/NetDissect-Lite/feature_operation.py", line 142, in tally_job
    for batch in pd.batches():
RuntimeError: generator raised StopIteration

I identify that it happens in the feature_operation.py when batch is None. 
What should I do? or do you know what is happening??

**Comment by aaossa** [comment]
I think this is a duplicated issue: https://github.com/CSAILVision/NetDissect-Lite/issues/18 and https://github.com/CSAILVision/NetDissect-Lite/issues/14

Maybe this answer (https://github.com/CSAILVision/NetDissect-Lite/issues/14#issuecomment-571269701) works for you

**Comment by fmorenovr** [comment]
> I think this is a duplicated issue: #18 and #14
> 
> Maybe this answer ([#14 (comment)](https://github.com/CSAILVision/NetDissect-Lite/issues/14#issuecomment-571269701)) works for you

I already solved it. But Thanks!!

**Comment by 2021202420** [comment]
Hey,I also encountered this problem, how did solve the problem? can you please share?
