### ISSUE TITLE
Eorror when running "python main.py" with MODEL = 'resnet50' 

### ISSUE THREAD

**Issue by shenw000** [CSAILVision/NetDissect-Lite#21]
I first ran "python main.py" command successfully with MODEL='resnet18' in the settings.py, which seems to indicate my environment works correctly.
Nest, I changed the settings.py to MODEL='resnet50' and encountered the following error:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    model = loadmodel(hook_feature)
  File "/media/sdb1/shenw/sandbox/netdissect/NetDissect-Lite/loader/model_loader.py", line 9, in loadmodel
    checkpoint = torch.load(settings.MODEL_FILE)
  File "/home/shenw/workspace/anaconda3/envs/pytorch-netdissect2/lib/python3.6/site-packages/torch/serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/shenw/workspace/anaconda3/envs/pytorch-netdissect2/lib/python3.6/site-packages/torch/serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/shenw/workspace/anaconda3/envs/pytorch-netdissect2/lib/python3.6/site-packages/torch/serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'zoo/whole_resnet50_places365_python36.pth.tar'
 
This error message seems to indicate that I didn't download the model file 'whole_resnet50_places365_python36.pth.tar'.
What is the fix for this error? Where can I find 'zoo/whole_resnet50_places365_python36.pth.tar' from your website?

**Comment by shenw000** [comment]
Just found where the model whole_resnet50_places365_python36.pth.tar can be donwloaded from.
There are 4 pre-trained models available:
http://places2.csail.mit.edu/models_places365/whole_alexnet_places365_python36.pth.tar
http://places2.csail.mit.edu/models_places365/whole_resnet18_places365_python36.pth.tar
http://places2.csail.mit.edu/models_places365/whole_resnet50_places365_python36.pth.tar
http://places2.csail.mit.edu/models_places365/whole_densenet161_places365_python36.pth.tar

Details about the models are at 
https://github.com/kywch/Vis_places365

![Screenshot from 2021-07-23 16-07-23](https://user-images.githubusercontent.com/9253528/126835870-f3e46190-3749-490a-8d50-b09cd7af0d58.png)
