### ISSUE TITLE
OverflowError: timeout value is too large

### ISSUE THREAD

**Issue by scutfrank** [CSAILVision/NetDissect-Lite#24]
**I just run the main.py in WIN10 system, and fix the scipy.misc problem by change import and sentence**
As I know ,Windows don't support multiprocessing,
So what I modify in the setting.py are
    WORKERS = 0

Got error like this:
Traceback (most recent call last):
  File "D:/1.Study/Jupyter Book/interpretable-ai-book-master/Chapter_06/NetDissect-Lite/main.py", line 11, in <module>
    features, maxfeature = fo.feature_extraction(model=model)
  File "D:\1.Study\Jupyter Book\interpretable-ai-book-master\Chapter_06\NetDissect-Lite\feature_operation.py", line 58, in feature_extraction
    for batch_idx,batch in enumerate(loader.tensor_batches(bgr_mean=self.mean)):
  File "D:\1.Study\Jupyter Book\interpretable-ai-book-master\Chapter_06\NetDissect-Lite\loader\data_loader.py", line 542, in tensor_batches
    batch = self.fetch_tensor_batch(
  File "D:\1.Study\Jupyter Book\interpretable-ai-book-master\Chapter_06\NetDissect-Lite\loader\data_loader.py", line 536, in fetch_tensor_batch
    batch = self.fetch_batch()
  File "D:\1.Study\Jupyter Book\interpretable-ai-book-master\Chapter_06\NetDissect-Lite\loader\data_loader.py", line 528, in fetch_batch
    return result.get(31536000)
  File "D:\Software\anaconda3\lib\multiprocessing\pool.py", line 765, in get
    self.wait(timeout)
  File "D:\Software\anaconda3\lib\multiprocessing\pool.py", line 762, in wait
    self._event.wait(timeout)
  File "D:\Software\anaconda3\lib\threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "D:\Software\anaconda3\lib\threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large
file missing, loading from scratch

Other question from me:
1.Is Win10 system possible to run the code(No multiprocessing and only has single GPU)? 
2.Can scipy.misc problem be fixed by change the sentence as below:
imread:
from scipy.misc import imread->import imageio
imread->imageio.imread
imsave:
from scipy.misc import imsave->import cv2 as cv
imsave->cv.imsave
imresize:
from scipy.misc import imresize->from PIL import Image
imresize(,)->np.array(Image.fromarray(arr).resize((,)))

Please help me with it ,thanks!

**Comment by gaotan666** [comment]
how to solve it?
